baseURL = "http://demo.themefisher.com/copper-hugo/"
disableLanguages = []
disqusShortname = "#"
googleAnalytics = ""
paginate = "6"
summaryLength = "10"
theme = "copper-hugo"
title = "Saskara Strategik"
[Languages.en]
contentDir = "content/english"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "faq"
name = "Faq"
weight = 1
[[Languages.en.menu.footer]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 2
[[Languages.en.menu.footer]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 3
[[Languages.en.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = "service"
name = "Service"
weight = 3
[[Languages.en.menu.main]]
URL = "team"
name = "Team"
weight = 4
[[Languages.en.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.en.menu.main]]
hasChildren = true
name = "Pages"
weight = 7
[[Languages.en.menu.main]]
URL = "career"
name = "Career"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "pricing-2"
name = "Pricing 2"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "how-it-works"
name = "How It Works"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "testimonial"
name = "Testimonial"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "faq"
name = "Faq"
parent = "Pages"
[[Languages.en.menu.main]]
URL = "changelog"
name = "Changelog"
parent = "Pages"
[Languages.fr]
contentDir = "content/french"
copyright = "Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/)"
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[[Languages.fr.menu.footer]]
URL = "faq"
name = "Faq"
weight = 1
[[Languages.fr.menu.footer]]
URL = "terms-conditions"
name = "Terms & Conditions"
weight = 2
[[Languages.fr.menu.footer]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 3
[[Languages.fr.menu.main]]
URL = "/"
name = "Home"
weight = 1
[[Languages.fr.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.fr.menu.main]]
URL = "service"
name = "Service"
weight = 3
[[Languages.fr.menu.main]]
URL = "team"
name = "Team"
weight = 4
[[Languages.fr.menu.main]]
URL = "blog"
name = "Blog"
weight = 5
[[Languages.fr.menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[[Languages.fr.menu.main]]
hasChildren = true
name = "Pages"
weight = 7
[[Languages.fr.menu.main]]
URL = "career"
name = "Career"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "pricing"
name = "Pricing"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "pricing-2"
name = "Pricing 2"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "how-it-works"
name = "How It Works"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "testimonial"
name = "Testimonial"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "faq"
name = "Faq"
parent = "Pages"
[[Languages.fr.menu.main]]
URL = "changelog"
name = "Changelog"
parent = "Pages"
[markup.goldmark.renderer]
unsafe = true
[outputs]
home = ["HTML", "RSS"]
[params]
author = "Themefisher"
contact_form_action = "https://formspree.io/f/xknyndll"
description = "Saskara Strategik"
logo = "images/logo.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/slick/slick-theme.css"
[[params.plugins.css]]
link = "plugins/aos/aos.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/aos/aos.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-whatsapp"
link = "#"
name = "Whatsapp"
[[params.social]]
icon = "ti-facebook"
link = "#"
name = "facebook"
[[params.social]]
icon = "ti-github"
link = "#"
name = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
name = "linkedin"
